### ISSUE TITLE
Specify iOS version

### ISSUE THREAD

**Issue by FrikkieSnyman** [mobile-dev-inc/bitrise-step-maestro-cloud-upload#2]
According to https://cloud.mobile.dev/reference/device-configuration#ios, we can pass `--ios-version` to the command to upload to Maestro Cloud.

This option is missing from the current bitrise recipe. How can we pass it in?

**Comment by FrikkieSnyman** [comment]
OH, actually I see it's already added in code, but I don't have version 1.2.0 of the recipe available in bitrise?

**Comment by ArthurSav** [comment]
This has been added.
